name: Get latest release version
on: [push]

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch release version
        run: |
          echo "installed version"
          node -p "require('./package.json').dependencies['monday-ui-style']"
          echo "latest version"
          npm show monday-ui-style version

          echo "CURRENT_VERSION=$(node -p "require('./package.json').dependencies['monday-ui-style']")" >> $GITHUB_ENV
          echo "LATEST_VERSION=$(npm show monday-ui-style version)" >> $GITHUB_ENV

      - name: Read release version
        run: |
          echo "var current"
          echo "${{ env.CURRENT_VERSION }}"
          echo "var latest"
          echo "${{ env.LATEST_VERSION }}"

      - name: Same version
        if: ${{ env.CURRENT_VERSION == env.LATEST_VERSION }}
        run: |
          echo "same version"

      - name: Not same version - install & check changes
        id: git-check
        if: ${{ env.CURRENT_VERSION != env.LATEST_VERSION }}
        run: |
          echo "Not same version"
          npm install monday-ui-style@${{env.LATEST_VERSION}}
          echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Commit latest changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          echo "commiting npm changes"
