name: Get latest release version
on: [push]

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch release version
        run: |
          echo "installed version"
          node -p "require('./package.json').dependencies['monday-ui-style']"
          echo "latest version"
          npm show monday-ui-style version

          echo "CURRENT_VERSION=$(node -p "require('./package.json').dependencies['monday-ui-style']")" >> $GITHUB_ENV
          echo "var current"
          echo $CURRENT_VERSION
          echo "LATEST_VERSION=$(npm show monday-ui-style version)" >> $GITHUB_ENV
          echo "var latest"
          echo $LATEST_VERSION
